The ``0-add_integer`` module
======================

Using ``add_integer``
-------------------
Importing function:
        >>> add_integer = __import__('0-add_integer').add_integer
        >>> add_integer(1, 2)
        3

Case with two small int:
        >>> add_integer(1, 2)
        3

Case with large num as first argument, and a negative:
        >>> add_integer(1e100, -2)
        10000000000000000159028911097599180468360808563945281389781327557747838772170381060813469985856815102

Case with large num as second argument, and a negative:
        >>> add_integer(-2, 1e100)
        10000000000000000159028911097599180468360808563945281389781327557747838772170381060813469985856815102

Case with one argument:
        >>> add_integer(2)
        100

Case with no arguments:
        >>> add_integer()
        Traceback (most recent call last):
        ...
        TypeError: add_integer() missing 1 required positional argument: 'a'

Case with three arguments:
        >>> add_integer(1, 2, 3)
        Traceback (most recent call last):
        ...
        TypeError: add_integer() takes from 1 to 2 positional arguments but 3 were given

Case with two int, one positive, one negative:
        >>> add_integer(100, -2)
        98

Case with two int, one negative, one positive:
        >>> add_integer(-2, 100)
        98

Case with float and negative:
        >>> add_integer(100.3, -2)
        98

Case with negative and float:
        >>> add_integer(-2, 100.3)
        98

Case with string as second argument:
        >>> add_integer(4, "School")
        Traceback (most recent call last):
        ...
        TypeError: b must be an integer

Case with None as argument:
        >>> add_integer(None)
        Traceback (most recent call last):
        ...
        TypeError: a must be an integer

Case with string as first argument:
        >>> add_integer("School", 2)
        Traceback (most recent call last):
        ...
        TypeError: a must be an integer

Case with Nan as first argument (empty variable):
        >>> add_integer(d, 100)
        Traceback (most recent call last):
        ...
        NameError: name 'd' is not defined

Case with Nan as second argument (empty variable):
        >>> add_integer(10, n)
        Traceback (most recent call last):
        ...
        NameError: name 'n' is not defined
